import React from 'react';
import { useNavigate } from 'react-router-dom';
import './Home.css';

function Home() {
  const navigate = useNavigate();
  const user = JSON.parse(localStorage.getItem('user') || 'null');

  return (
    <div className="home-container">
      <div className="home-content">
        <div className="hero-section">
          <h1 className="hero-title">
            Welcome to <span className="gradient-text">AI Interview Practice</span>
          </h1>
          <p className="hero-subtitle">
            Master your interview skills with AI-powered questions and real-time voice evaluation
          </p>
          
          {user && (
            <p className="welcome-message">
              Hello, <strong>{user.name}</strong>! Ready to practice?
            </p>
          )}

          <div className="cta-buttons">
            <button 
              className="btn btn-primary btn-large"
              onClick={() => navigate('/dashboard')}
            >
              Start Practicing 🚀
            </button>
            {user && (
              <button 
                className="btn btn-secondary btn-large"
                onClick={() => navigate('/progress')}
              >
                View My Progress 📊
              </button>
            )}
          </div>
        </div>

        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">🤖</div>
            <h3>AI-Powered Questions</h3>
            <p>Get personalized interview questions generated by Google Gemini AI based on your selected topic and difficulty</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🎤</div>
            <h3>Voice Recognition</h3>
            <p>Answer questions using your voice with real-time speech-to-text conversion powered by Web Speech API</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">⚡</div>
            <h3>Instant Feedback</h3>
            <p>Receive immediate AI evaluation with detailed feedback and scores to improve your answers</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">📈</div>
            <h3>Track Progress</h3>
            <p>Monitor your improvement over time with comprehensive statistics and session history</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🎯</div>
            <h3>Multiple Topics</h3>
            <p>Practice on JavaScript, React, Python, Data Structures, System Design, and many more topics</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">🏆</div>
            <h3>Difficulty Levels</h3>
            <p>Choose from Easy, Medium, or Hard difficulty levels to match your skill level and goals</p>
          </div>
        </div>

        <div className="stats-section">
          <div className="stat-item">
            <div className="stat-number">10+</div>
            <div className="stat-label">Topics Available</div>
          </div>
          <div className="stat-item">
            <div className="stat-number">AI</div>
            <div className="stat-label">Powered Evaluation</div>
          </div>
          <div className="stat-item">
            <div className="stat-number">∞</div>
            <div className="stat-label">Practice Sessions</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Home;
